
services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=n0m3l0
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-data:
  